### ISSUE TITLE
Edit of existing Event

### ISSUE THREAD

**Issue by Attix22** [Vierheller/Organizer#33] opened 2016-10-24 14:07 UTC
End Date is always Start Date + 1 day

Code Refactoring needed. It is basically one big blob right now

**Comment by 2xCmet** [comment] 2016-10-24 23:43
Maybe it is now fixed. 
I can't reproduce the Problem. But there was another Problem where the Text for the pickDateStart wasn't set to the Time of the Event.

**Closed as completed** 2016-10-25 16:45 UTC
